import Head from "next/head";
import styles from '../../styles/home.module.css';
import Image from "next/image";
import heroImg from '../../public/assets/hero.png'

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Tarefas plus | Organize sua tarefas de forma fácil</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/assets/favi.png" />
      </Head>

      <main className={styles.main}>

        <div className={styles.logoContent}>
          <Image
            src={heroImg}
            alt="Logo Tarefas Plus"
            className={styles.hero}
            priority
          />
        </div>

        <h1 className={styles.title}>
          Sistema para Organizar seus Estudos e Tarefas com Eficiência.
        </h1>

        <div className={styles.infoContent}>
          <section className={styles.box}>
            <span className={styles.span}>+ 12 post</span>
          </section>

          <section className={styles.box}>
            <span className={styles.span}>+ 90 comentários</span>
          </section>
        </div>

      </main>
    </div>
  );
}
